// ─────────────────────────────────────────────────────────────────────────────
//  FILE: references-data.js
//  AstroIndicators — Reference library content (English master).
//  These render as in-app readable pages. A "Translate" button on each guide
//  opens Google Translate in the user's chosen language (keeps build free & instant).
//
//  HOW TO EDIT: each guide is a list of sections. A section has a `h` (heading)
//  and `p` (one or more paragraphs). To change wording, edit the text in quotes.
// ─────────────────────────────────────────────────────────────────────────────

const REFERENCES = {

  // ════════════════════════════ THE 12 HOUSES ════════════════════════════
  houses: {
    title: "The 12 Houses",
    subtitle: "What each house governs — body, life, and karma",
    intro: "In Vedic astrology, the birth chart is divided into twelve houses (bhavas). Each house governs a specific set of life areas. The sign on a house, the planets sitting in it, and the strength of the planet that rules it together describe how that area of life unfolds. This guide explains each house in plain language — no prior knowledge assumed.",
    sections: [
      { h: "1st House — Lagna (The Self)",
        p: ["The first house is the ascendant, or Lagna — the sign rising on the eastern horizon at the moment of birth. It represents the self: your body, your physical constitution, your temperament, your overall vitality, and the lens through which the whole chart is read.",
            "A strong first house gives robust health, a clear sense of identity, and natural confidence. The planet that rules the first house (the Lagna lord) is one of the most important planets in the entire chart — its placement colours your whole life direction.",
            "Body parts: head, brain, overall constitution. Karaka (natural significator): the Sun."] },
      { h: "2nd House — Dhana (Wealth & Speech)",
        p: ["The second house governs accumulated wealth, savings, family lineage, food, and speech. It is not income earned (that is the eleventh) but what you hold and keep — your bank balance, possessions, and the family you were born into.",
            "It also rules the face, mouth, and voice — so it speaks to communication, honesty, and the way you express yourself verbally.",
            "Body parts: face, mouth, teeth, throat. Karaka: Jupiter (wealth) and Mercury (speech)."] },
      { h: "3rd House — Sahaja (Courage & Effort)",
        p: ["The third house represents courage, initiative, younger siblings, short journeys, hobbies, and the hands. It is the house of self-effort — the willingness to take action and push through resistance.",
            "Strong third house people are enterprising, brave, and skilled with their hands or in communication. It also governs writing, media, and personal skill.",
            "Body parts: arms, hands, shoulders, ears. Karaka: Mars."] },
      { h: "4th House — Sukha (Home & Heart)",
        p: ["The fourth house governs the mother, home, land, property, vehicles, emotional security, and inner peace (sukha means happiness). It is the foundation of the chart — the roots from which everything else grows.",
            "A strong fourth house gives emotional contentment, a stable home, and good relationships with the mother. It also rules education in its early and formative sense.",
            "Body parts: chest, heart, lungs. Karaka: the Moon (mother, mind) and Venus (vehicles, comforts)."] },
      { h: "5th House — Putra (Creativity & Children)",
        p: ["The fifth house represents intelligence, creativity, children, romance, speculation, and past-life merit (purva punya). It is the house of what you create — whether children, art, or ideas.",
            "It governs the capacity for joy, play, and genuine self-expression. It is also the house of mantras and devotion. A strong fifth house gives sharp intelligence and creative fertility.",
            "Body parts: upper abdomen, stomach. Karaka: Jupiter."] },
      { h: "6th House — Ari (Obstacles & Service)",
        p: ["The sixth house governs enemies, debts, disease, daily work, service, and obstacles. Though considered a difficult (dusthana) house, it is also the house of overcoming — the discipline to defeat what stands against you.",
            "It rules the capacity to work hard, to serve, to recover from illness, and to win in competition and litigation. Strong sixth-house people are resilient and good at handling adversity.",
            "Body parts: lower abdomen, intestines, kidneys. Karaka: Mars and Saturn."] },
      { h: "7th House — Yuvati (Partnership)",
        p: ["The seventh house governs marriage, the spouse, business partnerships, and all one-to-one relationships. It is directly opposite the first house — the 'other' to your 'self'.",
            "It also represents public dealings, contracts, and the general public. The condition of the seventh house and its lord describes the nature and quality of your closest partnerships.",
            "Body parts: lower back, reproductive organs. Karaka: Venus."] },
      { h: "8th House — Randhra (Transformation)",
        p: ["The eighth house governs longevity, sudden events, inheritance, joint resources, the occult, and deep transformation. It is the most mysterious house — the place of endings that become beginnings.",
            "It rules research, hidden things, and anything that requires going beneath the surface. Difficult when afflicted, but the source of profound depth and resilience when supported. It is also the house of the partner's wealth.",
            "Body parts: reproductive and excretory organs. Karaka: Saturn."] },
      { h: "9th House — Dharma (Fortune & Faith)",
        p: ["The ninth house is one of the most auspicious houses, governing fortune, higher wisdom, the father, gurus, long journeys, pilgrimage, and dharma (life purpose and ethics).",
            "It represents grace — the good luck that seems to arrive unearned, which classical astrology attributes to past-life merit. A strong ninth house gives faith, a good teacher, and a fortunate life direction.",
            "Body parts: hips, thighs. Karaka: Jupiter and the Sun (father)."] },
      { h: "10th House — Karma (Career & Status)",
        p: ["The tenth house governs career, profession, social status, authority, and public reputation. It sits at the highest point of the chart — what the world sees you achieve.",
            "It represents your action in the world (karma in the sense of work) and the recognition that follows. A strong tenth house gives a successful, visible career and respected standing.",
            "Body parts: knees, joints, bones. Karaka: the Sun, Mercury, Jupiter, and Saturn all signify career."] },
      { h: "11th House — Labha (Gains & Networks)",
        p: ["The eleventh house governs income, gains, profits, friends, networks, elder siblings, and the fulfilment of desires. Whatever the tenth house earns through work, the eleventh house is where it lands as actual gain.",
            "It rules large groups, communities, and the achievement of goals. A strong eleventh house gives steady income, helpful friends, and the realisation of ambitions.",
            "Body parts: calves, ankles. Karaka: Jupiter."] },
      { h: "12th House — Vyaya (Loss & Liberation)",
        p: ["The twelfth house governs loss, expenditure, foreign lands, isolation, sleep, and ultimately spiritual liberation (moksha). It is the house of letting go — of release, withdrawal, and surrender.",
            "Though associated with loss, it is also the house of the bed (rest and intimacy), of charity, of life abroad, and of the deepest spiritual practice. What the twelfth house 'loses' to the material world it gains for the soul.",
            "Body parts: feet, left eye. Karaka: Saturn (loss) and Ketu (liberation)."] },
      { h: "How to Read the Houses Together",
        p: ["No house works alone. The 'house lord' — the planet ruling the sign on that house — carries the house's energy to wherever it sits. For example, if the tenth lord (career) sits in the eleventh house (gains), career naturally produces income.",
            "Houses also fall into natural groups: the kendras (1, 4, 7, 10) are the pillars of the chart; the trikonas (1, 5, 9) are the houses of fortune and dharma; the dusthanas (6, 8, 12) are the houses of difficulty and growth. A planet's value depends heavily on which group it occupies.",
            "When reading any area of life, look at three things together: the house itself, the planets in it, and the strength and placement of its lord. The agreement or disagreement between these three tells the real story."] },
    ],
  },

  // ════════════════════════════ THE 9 PLANETS ════════════════════════════
  planets: {
    title: "The 9 Planets",
    subtitle: "The Navagraha — characteristics, significations, and periods",
    intro: "Vedic astrology recognises nine planets (Navagraha): the Sun, Moon, Mars, Mercury, Jupiter, Venus, Saturn, and the two lunar nodes Rahu and Ketu. Each planet governs certain themes, rules certain signs, and runs a planetary period (Mahadasha) of a fixed length. This guide introduces each one in plain language.",
    sections: [
      { h: "Sun — Surya (The Soul)",
        p: ["The Sun represents the soul, the ego, the father, authority, vitality, and self-expression. It is the king of the planetary cabinet — the source of light around which everything orbits.",
            "A strong Sun gives confidence, leadership, good health, and a clear sense of self. A weak or afflicted Sun can show low confidence, trouble with authority or father, or health issues related to the heart and bones.",
            "Rules: Leo. Exalted in Aries, debilitated in Libra. Mahadasha length: 6 years. Day: Sunday."] },
      { h: "Moon — Chandra (The Mind)",
        p: ["The Moon represents the mind, emotions, the mother, the public, and the inner world of feeling. In Vedic astrology the Moon is considered as important as the ascendant itself, because it governs how you experience everything.",
            "A strong Moon gives emotional stability, a calm mind, popularity, and a nurturing nature. A weak Moon can show emotional volatility, anxiety, or a difficult relationship with the mother.",
            "Rules: Cancer. Exalted in Taurus, debilitated in Scorpio. Mahadasha length: 10 years. Day: Monday."] },
      { h: "Mars — Mangala (Energy & Courage)",
        p: ["Mars represents energy, courage, action, aggression, siblings, property, and physical drive. It is the warrior and the commander — the force that pushes through obstacles.",
            "A strong Mars gives courage, discipline, athletic ability, and the will to act. An afflicted Mars can show anger, impulsiveness, accidents, or conflict. Mars also governs technical and engineering aptitude.",
            "Rules: Aries and Scorpio. Exalted in Capricorn, debilitated in Cancer. Mahadasha length: 7 years. Day: Tuesday."] },
      { h: "Mercury — Budha (Intellect & Communication)",
        p: ["Mercury represents intellect, communication, logic, commerce, writing, and analytical skill. It is the prince — quick, adaptable, and youthful — and the planet of the rational mind.",
            "A strong Mercury gives sharp intelligence, eloquence, business acumen, and skill with language and numbers. A weak Mercury can show confused thinking, nervousness, or difficulty communicating.",
            "Rules: Gemini and Virgo. Exalted in Virgo, debilitated in Pisces. Mahadasha length: 17 years. Day: Wednesday."] },
      { h: "Jupiter — Guru (Wisdom & Grace)",
        p: ["Jupiter represents wisdom, knowledge, teachers, children, wealth, dharma, and grace. It is the great benefic — the most naturally auspicious planet — and the guru of the gods.",
            "A strong Jupiter gives wisdom, optimism, generosity, good fortune, and spiritual inclination. Its placement shows where grace and expansion flow most easily in life. Jupiter's aspect on any house or planet protects and elevates it.",
            "Rules: Sagittarius and Pisces. Exalted in Cancer, debilitated in Capricorn. Mahadasha length: 16 years. Day: Thursday."] },
      { h: "Venus — Shukra (Love & Beauty)",
        p: ["Venus represents love, beauty, relationships, art, luxury, comfort, and pleasure. It is the other benefic — the guru of the demons — and governs all that makes life sweet.",
            "A strong Venus gives charm, artistic talent, a happy marriage, refinement, and material comforts. A weak Venus can show relationship difficulties or a lack of refinement. Venus also governs vehicles and the reproductive system.",
            "Rules: Taurus and Libra. Exalted in Pisces, debilitated in Virgo. Mahadasha length: 20 years. Day: Friday."] },
      { h: "Saturn — Shani (Discipline & Karma)",
        p: ["Saturn represents discipline, karma, time, patience, service, and hard-won maturity. It is the most demanding planet — the teacher who never gives easy grades — but its lessons, once learned, last a lifetime.",
            "A strong, well-placed Saturn gives endurance, integrity, organisational ability, and authority earned through genuine effort. Saturn rewards consistency and humility, and dismantles ego and shortcuts. For a complete treatment, see the dedicated Saturn guide.",
            "Rules: Capricorn and Aquarius. Exalted in Libra, debilitated in Aries. Mahadasha length: 19 years. Day: Saturday."] },
      { h: "Rahu — The North Node (Desire & Ambition)",
        p: ["Rahu is not a physical planet but a mathematical point — the north node of the Moon. It represents worldly desire, ambition, obsession, foreign things, technology, and sudden, unconventional rise.",
            "Rahu amplifies whatever it touches and creates intense craving for the matters of the house it sits in. It can give dramatic success but also illusion and dissatisfaction. It is the planet of the modern, the foreign, and the boundary-breaking.",
            "Exalted (by most traditions) in Taurus/Gemini. Mahadasha length: 18 years. Rahu has no day or rulership of its own."] },
      { h: "Ketu — The South Node (Detachment & Liberation)",
        p: ["Ketu is the south node of the Moon, directly opposite Rahu. It represents detachment, spirituality, past-life mastery, sudden loss, and ultimately liberation (moksha).",
            "Where Rahu craves, Ketu renounces. Ketu gives deep, intuitive, almost effortless skill in the matters of the house it occupies — often from past-life experience — alongside a sense that those matters no longer fully satisfy. It is the planet of the mystic and the seeker.",
            "Mahadasha length: 7 years. Like Rahu, Ketu has no day or sign rulership of its own."] },
      { h: "Planetary Friendships",
        p: ["Planets are not neutral toward one another — they have natural friends, enemies, and neutrals, which affect how they behave when placed together or in each other's signs.",
            "In brief: the Sun, Moon, Mars, and Jupiter form one broadly friendly group; Mercury, Venus, and Saturn form another. The Sun and Saturn are natural opposites (father and son in mythology, ego and its dissolution). Knowing these relationships helps explain why two planets together can either cooperate or create friction.",
            "When a planet sits in the sign of a friend, it expresses comfortably. In the sign of an enemy, it struggles. This is one of the key factors in judging a planet's real strength beyond its house position."] },
      { h: "How Planetary Periods Work",
        p: ["Each planet rules a Mahadasha (major period) of a fixed length, and the sequence runs in a set order: Sun (6 years), Moon (10), Mars (7), Rahu (18), Jupiter (16), Saturn (19), Mercury (17), Ketu (7), Venus (20) — totalling 120 years.",
            "Which period you are running depends on the Moon's exact position at birth. During any Mahadasha, that planet's themes — and its specific placement in your chart — come to the foreground of life. Within each major period run nine sub-periods (Antardashas), one for each planet, which colour the major period month to month.",
            "This is the engine behind the Dasa Periods feature of this app — it maps which planetary seasons you are moving through and what they tend to bring."] },
    ],
  },

  // ════════════════════════════ SATURN (from your guide) ════════════════════════════
  saturn: {
    title: "All About Saturn",
    subtitle: "The planet of karma, discipline, and liberation",
    intro: "Saturn (Shani) is perhaps the most misunderstood planet in Vedic astrology. It carries a reputation for difficulty and delay that is only partly deserved. This guide gives the complete picture: what Saturn is, what it genuinely asks of us, and how its three main expressions — Sade Sati, Saturn Mahadasha, and Saturn Antardasha — actually feel and what they are for. No prior knowledge is assumed.",
    sections: [
      { h: "Saturn in Simple Terms",
        p: ["Saturn is known as Shani — 'the one who moves slowly.' It is the slowest visible planet, taking about twenty-nine and a half years to circle the sky once. That slowness is its deepest teaching made visible: real things take real time.",
            "The simplest way to understand Saturn: imagine a teacher who never gives easy grades. Every mark must be earned through genuine effort. No shortcuts, no charm substituting for substance. That teacher is Saturn, and the class is your life.",
            "Saturn's placement in your chart shows where the most demanding, most meaningful, and ultimately most transformative work of your life will happen."] },
      { h: "What Saturn Governs",
        p: ["Saturn is the planet of karma — the consequences of past actions arriving in the present. It governs everything that accumulates slowly over time: the structures we build, the responsibilities we carry, the debts we settle, and the wisdom that only long experience produces.",
            "It rules discipline and structure (craftsman-like consistency, not harshness), obstacles and delay (redirection, not punishment), and service and humility (the ego's dissolution through genuinely serving others). In the body it rules the bones, joints, teeth, skin, and knees.",
            "Saturn is described in the classical texts as a malefic — a planet that creates friction — but 'malefic' does not mean 'evil'. A sculptor's chisel is not kind to the stone, but without that friction there is no sculpture."] },
      { h: "Saturn's Discipline — Understood Correctly",
        p: ["The word 'discipline' is the most misunderstood concept around Saturn. It is wrongly associated with rigidity, harshness, and the elimination of pleasure. Saturn's archetype is not the soldier in a barracks — it is the master craftsman, who works with deep consistency but also knows the chisel must rest.",
            "Discipline in Saturn's lens means three things: consistently showing up and finishing what was started; structural integrity (doing what you said you would do); and purposeful rest built into the structure. A practice maintained moderately without interruption carries far more Saturnine energy than an intense burst followed by collapse.",
            "Saturn is profoundly moved by steadiness and deeply unimpressed by intensity."] },
      { h: "The Three Needs Saturn Distinguishes",
        p: ["Saturn asks one question of any activity: is this nourishing the soul or numbing the wound? It treats three kinds of need very differently.",
            "Body needs (rest, food, warmth, genuine physical pleasure) are fully honoured — Saturn does not ask you to damage the body in the name of discipline. Soul needs (meaning, purpose, connection, creative expression) are actively supported — they are what the discipline is building toward.",
            "Only the ego's needs (recognition, status, performing virtue to be seen) are dismantled — and not harshly, but through the steady withdrawal of the validation the ego craves until it learns to act without needing it."] },
      { h: "Sade Sati — Saturn's Transit Over the Moon",
        p: ["Sade Sati ('seven and a half') is the seven-and-a-half-year period when Saturn transits the three signs centred on your natal Moon sign. It happens to everyone with the same Moon sign at the same time — it is collective, like weather.",
            "It runs in three phases of about two and a half years each: Rising (a subtle, hard-to-name heaviness), Peak (Saturn directly over the Moon — maximum weight, the most intense phase), and Setting (gradual relief as the pressure lifts).",
            "Sade Sati feels like something is being taken away — but it is never something you genuinely needed. It dismantles the emotional scaffolding you have built your sense of security on, revealing that you are more resilient than you believed. Those who navigate it consciously report a quality of inner freedom on the other side."] },
      { h: "What Makes Sade Sati Easier or Harder",
        p: ["Not all Sade Sati experiences are equal. A Moon that is strong in the birth chart — in a friendly sign, aspected by Jupiter, or exalted — experiences it as restructuring rather than acute suffering. A Moon already under pressure experiences it more intensely.",
            "Jupiter aspecting the natal Moon during Sade Sati provides meaningful protection — the most graceful softening available. Running a Jupiter or Venus Mahadasha during the period also helps counter the weight.",
            "Above all, conscious engagement — understanding what the period is asking and meeting it with openness rather than resistance — genuinely reduces its felt intensity."] },
      { h: "Saturn Mahadasha — The 19-Year Curriculum",
        p: ["Saturn's Mahadasha lasts nineteen years. Unlike Sade Sati (a transit that happens to everyone), the Mahadasha is unique to you — when it falls depends on your exact birth, and during it Saturn's natal position becomes the operating system of your life.",
            "It moves through five recognisable phases: Storm 1 (the first raw encounter with the karma), a Grace Period (reward for early honest work — the richest external window), an Emotional Valley (the deepest inner phase), Storm 2 (the final examination), and Liberation (the curriculum closing in grace).",
            "Saturn Mahadasha does not take — it refines. Everything it removes was either not genuinely yours to keep, or was preventing something more authentically yours from arriving. This is hard to live but consistently reported by those who navigate it consciously."] },
      { h: "Saturn Antardasha Within Other Periods",
        p: ["Saturn also appears as a sub-period (Antardasha) within every other planet's Mahadasha — so everyone experiences it many times across life. Its quality depends heavily on the host planet.",
            "Within Jupiter's period it creates the most productive combination in the system — wisdom meeting discipline, often life's most meaningful work. Within Venus, it brings seriousness to relationships and creativity. Within Rahu, it is among the most demanding — craving meeting restraint. Within the Sun, it stages the classic tension between ego and earned authority.",
            "Regardless of the host, Saturn's sub-period always rewards the same thing — showing up to what is genuinely worth doing, without needing to be seen doing it — and always presses on the same wound: anywhere the ego is performing discipline rather than living it."] },
      { h: "Remedies — Working With Saturn",
        p: ["One principle must be clear first: no remedy bypasses Saturn's lesson. Remedies do not make Saturn go away — they change the quality of your relationship with its energy, making you more receptive and less resistant. The outer practice supports the inner work; it never replaces it.",
            "Practical remedies include Saturn seva (anonymous service to the elderly, labourers, animals — especially done on Saturdays without seeking acknowledgement), feeding crows on Saturday, the Mahamrityunjaya mantra, and maintaining a Thursday practice honouring Jupiter, Saturn's natural moderator.",
            "But the irreplaceable foundation is honest self-awareness about the ego's role in your own suffering — being willing to see clearly when difficulty is being prolonged by the ego's resistance to releasing what it was never entitled to hold. That willingness to see is what every remedy is designed to support."] },
      { h: "In Closing",
        p: ["Saturn is the planet that will not let you settle for less than what you are genuinely capable of becoming. It does not meet you with warmth — it meets you with honesty. It does not offer comfort — it offers the rarer gift of reality, clearly seen.",
            "The person who finishes a Saturn period having met it consciously is rarely the same person who entered it. Not because Saturn gave them something, but because it revealed they were always capable of more than they were allowing themselves to access.",
            "That is not cruelty. It is the most committed form of teaching available in the planetary system — and knowing that is what transforms Saturn from the most feared planet into the most trusted one."] },
    ],
  },

};

if (typeof window !== "undefined") window.REFERENCES = REFERENCES;
