// ─────────────────────────────────────────────────────────────────────────────
//  FILE: references-data.js
//  AstroIndicators — Reference library content (English master).
//  These render as in-app readable pages. A "Translate" button on each guide
//  opens Google Translate in the user's chosen language (keeps build free & instant).
//
//  HOW TO EDIT: each guide is a list of sections. A section has a `h` (heading)
//  and `p` (one or more paragraphs). To change wording, edit the text in quotes.
// ─────────────────────────────────────────────────────────────────────────────

const REFERENCES = {

  // ════════════════════════════ THE 12 HOUSES ════════════════════════════
  houses: {
    title: "The 12 Houses",
    subtitle: "What each house governs — body, life, and karma",
    intro: "In Vedic astrology, the birth chart is divided into twelve houses (bhavas). Each house governs a specific set of life areas. The sign on a house, the planets sitting in it, and the strength of the planet that rules it together describe how that area of life unfolds. This guide explains each house in plain language — no prior knowledge assumed.",
    sections: [
      { h: "1st House — Lagna (The Self)",
        p: ["The first house is the ascendant, or Lagna — the sign rising on the eastern horizon at the moment of birth. It represents the self: your body, your physical constitution, your temperament, your overall vitality, and the lens through which the whole chart is read.",
            "A strong first house gives robust health, a clear sense of identity, and natural confidence. The planet that rules the first house (the Lagna lord) is one of the most important planets in the entire chart — its placement colours your whole life direction.",
            "Body parts: head, brain, overall constitution. Karaka (natural significator): the Sun."] },
      { h: "2nd House — Dhana (Wealth & Speech)",
        p: ["The second house governs accumulated wealth, savings, family lineage, food, and speech. It is not income earned (that is the eleventh) but what you hold and keep — your bank balance, possessions, and the family you were born into.",
            "It also rules the face, mouth, and voice — so it speaks to communication, honesty, and the way you express yourself verbally.",
            "Body parts: face, mouth, teeth, throat. Karaka: Jupiter (wealth) and Mercury (speech)."] },
      { h: "3rd House — Sahaja (Courage & Effort)",
        p: ["The third house represents courage, initiative, younger siblings, short journeys, hobbies, and the hands. It is the house of self-effort — the willingness to take action and push through resistance.",
            "Strong third house people are enterprising, brave, and skilled with their hands or in communication. It also governs writing, media, and personal skill.",
            "Body parts: arms, hands, shoulders, ears. Karaka: Mars."] },
      { h: "4th House — Sukha (Home & Heart)",
        p: ["The fourth house governs the mother, home, land, property, vehicles, emotional security, and inner peace (sukha means happiness). It is the foundation of the chart — the roots from which everything else grows.",
            "A strong fourth house gives emotional contentment, a stable home, and good relationships with the mother. It also rules education in its early and formative sense.",
            "Body parts: chest, heart, lungs. Karaka: the Moon (mother, mind) and Venus (vehicles, comforts)."] },
      { h: "5th House — Putra (Creativity & Children)",
        p: ["The fifth house represents intelligence, creativity, children, romance, speculation, and past-life merit (purva punya). It is the house of what you create — whether children, art, or ideas.",
            "It governs the capacity for joy, play, and genuine self-expression. It is also the house of mantras and devotion. A strong fifth house gives sharp intelligence and creative fertility.",
            "Body parts: upper abdomen, stomach. Karaka: Jupiter."] },
      { h: "6th House — Ari (Obstacles & Service)",
        p: ["The sixth house governs enemies, debts, disease, daily work, service, and obstacles. Though considered a difficult (dusthana) house, it is also the house of overcoming — the discipline to defeat what stands against you.",
            "It rules the capacity to work hard, to serve, to recover from illness, and to win in competition and litigation. Strong sixth-house people are resilient and good at handling adversity.",
            "Body parts: lower abdomen, intestines, kidneys. Karaka: Mars and Saturn."] },
      { h: "7th House — Yuvati (Partnership)",
        p: ["The seventh house governs marriage, the spouse, business partnerships, and all one-to-one relationships. It is directly opposite the first house — the 'other' to your 'self'.",
            "It also represents public dealings, contracts, and the general public. The condition of the seventh house and its lord describes the nature and quality of your closest partnerships.",
            "Body parts: lower back, reproductive organs. Karaka: Venus."] },
      { h: "8th House — Randhra (Transformation)",
        p: ["The eighth house governs longevity, sudden events, inheritance, joint resources, the occult, and deep transformation. It is the most mysterious house — the place of endings that become beginnings.",
            "It rules research, hidden things, and anything that requires going beneath the surface. Difficult when afflicted, but the source of profound depth and resilience when supported. It is also the house of the partner's wealth.",
            "Body parts: reproductive and excretory organs. Karaka: Saturn."] },
      { h: "9th House — Dharma (Fortune & Faith)",
        p: ["The ninth house is one of the most auspicious houses, governing fortune, higher wisdom, the father, gurus, long journeys, pilgrimage, and dharma (life purpose and ethics).",
            "It represents grace — the good luck that seems to arrive unearned, which classical astrology attributes to past-life merit. A strong ninth house gives faith, a good teacher, and a fortunate life direction.",
            "Body parts: hips, thighs. Karaka: Jupiter and the Sun (father)."] },
      { h: "10th House — Karma (Career & Status)",
        p: ["The tenth house governs career, profession, social status, authority, and public reputation. It sits at the highest point of the chart — what the world sees you achieve.",
            "It represents your action in the world (karma in the sense of work) and the recognition that follows. A strong tenth house gives a successful, visible career and respected standing.",
            "Body parts: knees, joints, bones. Karaka: the Sun, Mercury, Jupiter, and Saturn all signify career."] },
      { h: "11th House — Labha (Gains & Networks)",
        p: ["The eleventh house governs income, gains, profits, friends, networks, elder siblings, and the fulfilment of desires. Whatever the tenth house earns through work, the eleventh house is where it lands as actual gain.",
            "It rules large groups, communities, and the achievement of goals. A strong eleventh house gives steady income, helpful friends, and the realisation of ambitions.",
            "Body parts: calves, ankles. Karaka: Jupiter."] },
      { h: "12th House — Vyaya (Loss & Liberation)",
        p: ["The twelfth house governs loss, expenditure, foreign lands, isolation, sleep, and ultimately spiritual liberation (moksha). It is the house of letting go — of release, withdrawal, and surrender.",
            "Though associated with loss, it is also the house of the bed (rest and intimacy), of charity, of life abroad, and of the deepest spiritual practice. What the twelfth house 'loses' to the material world it gains for the soul.",
            "Body parts: feet, left eye. Karaka: Saturn (loss) and Ketu (liberation)."] },
      { h: "How to Read the Houses Together",
        p: ["No house works alone. The 'house lord' — the planet ruling the sign on that house — carries the house's energy to wherever it sits. For example, if the tenth lord (career) sits in the eleventh house (gains), career naturally produces income.",
            "Houses also fall into natural groups: the kendras (1, 4, 7, 10) are the pillars of the chart; the trikonas (1, 5, 9) are the houses of fortune and dharma; the dusthanas (6, 8, 12) are the houses of difficulty and growth. A planet's value depends heavily on which group it occupies.",
            "When reading any area of life, look at three things together: the house itself, the planets in it, and the strength and placement of its lord. The agreement or disagreement between these three tells the real story."] },
    ],
  },

  // ════════════════════════════ THE 9 PLANETS ════════════════════════════
  planets: {
    title: "The 9 Planets",
    subtitle: "The Navagraha — characteristics, significations, and periods",
    intro: "Vedic astrology recognises nine planets (Navagraha): the Sun, Moon, Mars, Mercury, Jupiter, Venus, Saturn, and the two lunar nodes Rahu and Ketu. Each planet governs certain themes, rules certain signs, and runs a planetary period (Mahadasha) of a fixed length. This guide introduces each one in plain language.",
    sections: [
      { h: "Sun — Surya (The Soul)",
        p: ["The Sun represents the soul, the ego, the father, authority, vitality, and self-expression. It is the king of the planetary cabinet — the source of light around which everything orbits.",
            "A strong Sun gives confidence, leadership, good health, and a clear sense of self. A weak or afflicted Sun can show low confidence, trouble with authority or father, or health issues related to the heart and bones.",
            "Rules: Leo. Exalted in Aries, debilitated in Libra. Mahadasha length: 6 years. Day: Sunday."] },
      { h: "Moon — Chandra (The Mind)",
        p: ["The Moon represents the mind, emotions, the mother, the public, and the inner world of feeling. In Vedic astrology the Moon is considered as important as the ascendant itself, because it governs how you experience everything.",
            "A strong Moon gives emotional stability, a calm mind, popularity, and a nurturing nature. A weak Moon can show emotional volatility, anxiety, or a difficult relationship with the mother.",
            "Rules: Cancer. Exalted in Taurus, debilitated in Scorpio. Mahadasha length: 10 years. Day: Monday."] },
      { h: "Mars — Mangala (Energy & Courage)",
        p: ["Mars represents energy, courage, action, aggression, siblings, property, and physical drive. It is the warrior and the commander — the force that pushes through obstacles.",
            "A strong Mars gives courage, discipline, athletic ability, and the will to act. An afflicted Mars can show anger, impulsiveness, accidents, or conflict. Mars also governs technical and engineering aptitude.",
            "Rules: Aries and Scorpio. Exalted in Capricorn, debilitated in Cancer. Mahadasha length: 7 years. Day: Tuesday."] },
      { h: "Mercury — Budha (Intellect & Communication)",
        p: ["Mercury represents intellect, communication, logic, commerce, writing, and analytical skill. It is the prince — quick, adaptable, and youthful — and the planet of the rational mind.",
            "A strong Mercury gives sharp intelligence, eloquence, business acumen, and skill with language and numbers. A weak Mercury can show confused thinking, nervousness, or difficulty communicating.",
            "Rules: Gemini and Virgo. Exalted in Virgo, debilitated in Pisces. Mahadasha length: 17 years. Day: Wednesday."] },
      { h: "Jupiter — Guru (Wisdom & Grace)",
        p: ["Jupiter represents wisdom, knowledge, teachers, children, wealth, dharma, and grace. It is the great benefic — the most naturally auspicious planet — and the guru of the gods.",
            "A strong Jupiter gives wisdom, optimism, generosity, good fortune, and spiritual inclination. Its placement shows where grace and expansion flow most easily in life. Jupiter's aspect on any house or planet protects and elevates it.",
            "Rules: Sagittarius and Pisces. Exalted in Cancer, debilitated in Capricorn. Mahadasha length: 16 years. Day: Thursday."] },
      { h: "Venus — Shukra (Love & Beauty)",
        p: ["Venus represents love, beauty, relationships, art, luxury, comfort, and pleasure. It is the other benefic — the guru of the demons — and governs all that makes life sweet.",
            "A strong Venus gives charm, artistic talent, a happy marriage, refinement, and material comforts. A weak Venus can show relationship difficulties or a lack of refinement. Venus also governs vehicles and the reproductive system.",
            "Rules: Taurus and Libra. Exalted in Pisces, debilitated in Virgo. Mahadasha length: 20 years. Day: Friday."] },
      { h: "Saturn — Shani (Discipline & Karma)",
        p: ["Saturn represents discipline, karma, time, patience, service, and hard-won maturity. It is the most demanding planet — the teacher who never gives easy grades — but its lessons, once learned, last a lifetime.",
            "A strong, well-placed Saturn gives endurance, integrity, organisational ability, and authority earned through genuine effort. Saturn rewards consistency and humility, and dismantles ego and shortcuts. For a complete treatment, see the dedicated Saturn guide.",
            "Rules: Capricorn and Aquarius. Exalted in Libra, debilitated in Aries. Mahadasha length: 19 years. Day: Saturday."] },
      { h: "Rahu — The North Node (Desire & Ambition)",
        p: ["Rahu is not a physical planet but a mathematical point — the north node of the Moon. It represents worldly desire, ambition, obsession, foreign things, technology, and sudden, unconventional rise.",
            "Rahu amplifies whatever it touches and creates intense craving for the matters of the house it sits in. It can give dramatic success but also illusion and dissatisfaction. It is the planet of the modern, the foreign, and the boundary-breaking.",
            "Exalted (by most traditions) in Taurus/Gemini. Mahadasha length: 18 years. Rahu has no day or rulership of its own."] },
      { h: "Ketu — The South Node (Detachment & Liberation)",
        p: ["Ketu is the south node of the Moon, directly opposite Rahu. It represents detachment, spirituality, past-life mastery, sudden loss, and ultimately liberation (moksha).",
            "Where Rahu craves, Ketu renounces. Ketu gives deep, intuitive, almost effortless skill in the matters of the house it occupies — often from past-life experience — alongside a sense that those matters no longer fully satisfy. It is the planet of the mystic and the seeker.",
            "Mahadasha length: 7 years. Like Rahu, Ketu has no day or sign rulership of its own."] },
      { h: "Planetary Friendships",
        p: ["Planets are not neutral toward one another — they have natural friends, enemies, and neutrals, which affect how they behave when placed together or in each other's signs.",
            "In brief: the Sun, Moon, Mars, and Jupiter form one broadly friendly group; Mercury, Venus, and Saturn form another. The Sun and Saturn are natural opposites (father and son in mythology, ego and its dissolution). Knowing these relationships helps explain why two planets together can either cooperate or create friction.",
            "When a planet sits in the sign of a friend, it expresses comfortably. In the sign of an enemy, it struggles. This is one of the key factors in judging a planet's real strength beyond its house position."] },
      { h: "How Planetary Periods Work",
        p: ["Each planet rules a Mahadasha (major period) of a fixed length, and the sequence runs in a set order: Sun (6 years), Moon (10), Mars (7), Rahu (18), Jupiter (16), Saturn (19), Mercury (17), Ketu (7), Venus (20) — totalling 120 years.",
            "Which period you are running depends on the Moon's exact position at birth. During any Mahadasha, that planet's themes — and its specific placement in your chart — come to the foreground of life. Within each major period run nine sub-periods (Antardashas), one for each planet, which colour the major period month to month.",
            "This is the engine behind the Dasa Periods feature of this app — it maps which planetary seasons you are moving through and what they tend to bring."] },
    ],
  },

  // ════════════════════════════ SATURN (from your guide) ════════════════════════════
  saturn: {
    title: "All About Saturn",
    subtitle: "The planet of karma, discipline, and liberation",
    intro: "Saturn (Shani) is perhaps the most misunderstood planet in Vedic astrology. It carries a reputation for difficulty and delay that is only partly deserved. This guide gives the complete picture: what Saturn is, what it genuinely asks of us, and how its three main expressions — Sade Sati, Saturn Mahadasha, and Saturn Antardasha — actually feel and what they are for. No prior knowledge is assumed.",
    sections: [
      { h: "Saturn in Simple Terms",
        p: ["Saturn is known as Shani — 'the one who moves slowly.' It is the slowest visible planet, taking about twenty-nine and a half years to circle the sky once. That slowness is its deepest teaching made visible: real things take real time.",
            "The simplest way to understand Saturn: imagine a teacher who never gives easy grades. Every mark must be earned through genuine effort. No shortcuts, no charm substituting for substance. That teacher is Saturn, and the class is your life.",
            "Saturn's placement in your chart shows where the most demanding, most meaningful, and ultimately most transformative work of your life will happen."] },
      { h: "What Saturn Governs",
        p: ["Saturn is the planet of karma — the consequences of past actions arriving in the present. It governs everything that accumulates slowly over time: the structures we build, the responsibilities we carry, the debts we settle, and the wisdom that only long experience produces.",
            "It rules discipline and structure (craftsman-like consistency, not harshness), obstacles and delay (redirection, not punishment), and service and humility (the ego's dissolution through genuinely serving others). In the body it rules the bones, joints, teeth, skin, and knees.",
            "Saturn is described in the classical texts as a malefic — a planet that creates friction — but 'malefic' does not mean 'evil'. A sculptor's chisel is not kind to the stone, but without that friction there is no sculpture."] },
      { h: "Saturn's Discipline — Understood Correctly",
        p: ["The word 'discipline' is the most misunderstood concept around Saturn. It is wrongly associated with rigidity, harshness, and the elimination of pleasure. Saturn's archetype is not the soldier in a barracks — it is the master craftsman, who works with deep consistency but also knows the chisel must rest.",
            "Discipline in Saturn's lens means three things: consistently showing up and finishing what was started; structural integrity (doing what you said you would do); and purposeful rest built into the structure. A practice maintained moderately without interruption carries far more Saturnine energy than an intense burst followed by collapse.",
            "Saturn is profoundly moved by steadiness and deeply unimpressed by intensity."] },
      { h: "The Three Needs Saturn Distinguishes",
        p: ["Saturn asks one question of any activity: is this nourishing the soul or numbing the wound? It treats three kinds of need very differently.",
            "Body needs (rest, food, warmth, genuine physical pleasure) are fully honoured — Saturn does not ask you to damage the body in the name of discipline. Soul needs (meaning, purpose, connection, creative expression) are actively supported — they are what the discipline is building toward.",
            "Only the ego's needs (recognition, status, performing virtue to be seen) are dismantled — and not harshly, but through the steady withdrawal of the validation the ego craves until it learns to act without needing it."] },
      { h: "Sade Sati — Saturn's Transit Over the Moon",
        p: ["Sade Sati ('seven and a half') is the seven-and-a-half-year period when Saturn transits the three signs centred on your natal Moon sign. It happens to everyone with the same Moon sign at the same time — it is collective, like weather.",
            "It runs in three phases of about two and a half years each: Rising (a subtle, hard-to-name heaviness), Peak (Saturn directly over the Moon — maximum weight, the most intense phase), and Setting (gradual relief as the pressure lifts).",
            "Sade Sati feels like something is being taken away — but it is never something you genuinely needed. It dismantles the emotional scaffolding you have built your sense of security on, revealing that you are more resilient than you believed. Those who navigate it consciously report a quality of inner freedom on the other side."] },
      { h: "What Makes Sade Sati Easier or Harder",
        p: ["Not all Sade Sati experiences are equal. A Moon that is strong in the birth chart — in a friendly sign, aspected by Jupiter, or exalted — experiences it as restructuring rather than acute suffering. A Moon already under pressure experiences it more intensely.",
            "Jupiter aspecting the natal Moon during Sade Sati provides meaningful protection — the most graceful softening available. Running a Jupiter or Venus Mahadasha during the period also helps counter the weight.",
            "Above all, conscious engagement — understanding what the period is asking and meeting it with openness rather than resistance — genuinely reduces its felt intensity."] },
      { h: "Saturn Mahadasha — The 19-Year Curriculum",
        p: ["Saturn's Mahadasha lasts nineteen years. Unlike Sade Sati (a transit that happens to everyone), the Mahadasha is unique to you — when it falls depends on your exact birth, and during it Saturn's natal position becomes the operating system of your life.",
            "It moves through five recognisable phases: Storm 1 (the first raw encounter with the karma), a Grace Period (reward for early honest work — the richest external window), an Emotional Valley (the deepest inner phase), Storm 2 (the final examination), and Liberation (the curriculum closing in grace).",
            "Saturn Mahadasha does not take — it refines. Everything it removes was either not genuinely yours to keep, or was preventing something more authentically yours from arriving. This is hard to live but consistently reported by those who navigate it consciously."] },
      { h: "Saturn Antardasha Within Other Periods",
        p: ["Saturn also appears as a sub-period (Antardasha) within every other planet's Mahadasha — so everyone experiences it many times across life. Its quality depends heavily on the host planet.",
            "Within Jupiter's period it creates the most productive combination in the system — wisdom meeting discipline, often life's most meaningful work. Within Venus, it brings seriousness to relationships and creativity. Within Rahu, it is among the most demanding — craving meeting restraint. Within the Sun, it stages the classic tension between ego and earned authority.",
            "Regardless of the host, Saturn's sub-period always rewards the same thing — showing up to what is genuinely worth doing, without needing to be seen doing it — and always presses on the same wound: anywhere the ego is performing discipline rather than living it."] },
      { h: "Remedies — Working With Saturn",
        p: ["One principle must be clear first: no remedy bypasses Saturn's lesson. Remedies do not make Saturn go away — they change the quality of your relationship with its energy, making you more receptive and less resistant. The outer practice supports the inner work; it never replaces it.",
            "Practical remedies include Saturn seva (anonymous service to the elderly, labourers, animals — especially done on Saturdays without seeking acknowledgement), feeding crows on Saturday, the Mahamrityunjaya mantra, and maintaining a Thursday practice honouring Jupiter, Saturn's natural moderator.",
            "But the irreplaceable foundation is honest self-awareness about the ego's role in your own suffering — being willing to see clearly when difficulty is being prolonged by the ego's resistance to releasing what it was never entitled to hold. That willingness to see is what every remedy is designed to support."] },
      { h: "In Closing",
        p: ["Saturn is the planet that will not let you settle for less than what you are genuinely capable of becoming. It does not meet you with warmth — it meets you with honesty. It does not offer comfort — it offers the rarer gift of reality, clearly seen.",
            "The person who finishes a Saturn period having met it consciously is rarely the same person who entered it. Not because Saturn gave them something, but because it revealed they were always capable of more than they were allowing themselves to access.",
            "That is not cruelty. It is the most committed form of teaching available in the planetary system — and knowing that is what transforms Saturn from the most feared planet into the most trusted one."] },
    ],
  },

};

// ════════════════════ TAMIL TRANSLATIONS (in-place) ════════════════════
REFERENCES.houses.langs = {
  TA: {
    title: "12 வீடுகள்",
    subtitle: "ஒவ்வொரு வீடும் எதை ஆளுகிறது — உடல், வாழ்க்கை, கர்மா",
    intro: "வேத ஜோதிடத்தில், ஜாதகம் பன்னிரண்டு வீடுகளாக (பாவங்கள்) பிரிக்கப்பட்டுள்ளது. ஒவ்வொரு வீடும் வாழ்க்கையின் குறிப்பிட்ட பகுதிகளை ஆளுகிறது. ஒரு வீட்டின் ராசி, அதில் அமர்ந்துள்ள கிரகங்கள், அந்த வீட்டை ஆளும் கிரகத்தின் வலிமை ஆகியவை சேர்ந்து அந்த வாழ்க்கைப் பகுதி எவ்வாறு வெளிப்படுகிறது என்பதை விவரிக்கின்றன.",
    sections: [
      { h: "1ஆம் வீடு — லக்னம் (சுயம்)", p: ["முதல் வீடு லக்னம் — பிறக்கும் தருணத்தில் கிழக்கு அடிவானத்தில் உதயமாகும் ராசி. இது சுயத்தை குறிக்கிறது: உடல், உடல் அமைப்பு, மனநிலை, ஒட்டுமொத்த உயிர்ச்சக்தி.", "வலுவான முதல் வீடு வலுவான ஆரோக்கியம், தெளிவான அடையாளம், இயல்பான நம்பிக்கை தருகிறது. லக்னாதிபதி ஜாதகத்தின் மிக முக்கியமான கிரகங்களில் ஒன்று.", "உடல் பாகங்கள்: தலை, மூளை. காரகன்: சூரியன்."] },
      { h: "2ஆம் வீடு — தனம் (செல்வம் & பேச்சு)", p: ["இரண்டாம் வீடு சேமித்த செல்வம், குடும்ப பரம்பரை, உணவு, பேச்சை ஆளுகிறது. இது சம்பாதித்த வருமானம் அல்ல (அது 11ஆம் வீடு) ஆனால் நீங்கள் வைத்திருப்பது.", "இது முகம், வாய், குரலையும் ஆளுகிறது — எனவே தொடர்பு மற்றும் வாய்மொழி வெளிப்பாடு.", "உடல் பாகங்கள்: முகம், வாய், பற்கள், தொண்டை. காரகன்: குரு (செல்வம்), புதன் (பேச்சு)."] },
      { h: "3ஆம் வீடு — சகஜ (தைரியம் & முயற்சி)", p: ["மூன்றாம் வீடு தைரியம், முன்முயற்சி, இளைய உடன்பிறந்தோர், குறுகிய பயணங்கள், கைகளை குறிக்கிறது. இது சுய முயற்சியின் வீடு.", "வலுவான மூன்றாம் வீட்டினர் துணிச்சல் மிக்கவர்கள், கைத்திறன் உள்ளவர்கள். எழுத்து மற்றும் ஊடகத்தையும் ஆளுகிறது.", "உடல் பாகங்கள்: கைகள், தோள்கள், காதுகள். காரகன்: செவ்வாய்."] },
      { h: "4ஆம் வீடு — சுக (வீடு & இதயம்)", p: ["நான்காம் வீடு தாய், வீடு, நிலம், சொத்து, வாகனங்கள், உணர்ச்சி பாதுகாப்பு, உள் அமைதியை ஆளுகிறது. இது ஜாதகத்தின் அடித்தளம்.", "வலுவான நான்காம் வீடு உணர்ச்சி திருப்தி, நிலையான வீடு, தாயுடன் நல்ல உறவு தருகிறது.", "உடல் பாகங்கள்: மார்பு, இதயம், நுரையீரல். காரகன்: சந்திரன் (தாய்), சுக்கிரன் (வாகனங்கள்)."] },
      { h: "5ஆம் வீடு — புத்ர (படைப்பாற்றல் & குழந்தைகள்)", p: ["ஐந்தாம் வீடு புத்திசாலித்தனம், படைப்பாற்றல், குழந்தைகள், காதல், ஊகம், முற்பிறவி புண்ணியத்தை குறிக்கிறது.", "இது மகிழ்ச்சி, விளையாட்டு, உண்மையான சுய வெளிப்பாட்டின் திறனை ஆளுகிறது. மந்திரங்கள் மற்றும் பக்தியின் வீடும் கூட.", "உடல் பாகங்கள்: மேல் வயிறு, இரைப்பை. காரகன்: குரு."] },
      { h: "6ஆம் வீடு — அரி (தடைகள் & சேவை)", p: ["ஆறாம் வீடு எதிரிகள், கடன்கள், நோய், அன்றாட வேலை, சேவை, தடைகளை ஆளுகிறது. கடினமான வீடாக கருதப்பட்டாலும், இது வெல்லுதலின் வீடும் கூட.", "கடினமாக உழைக்கும், சேவை செய்யும், நோயிலிருந்து மீளும், போட்டியில் வெல்லும் திறனை ஆளுகிறது.", "உடல் பாகங்கள்: கீழ் வயிறு, குடல், சிறுநீரகம். காரகன்: செவ்வாய், சனி."] },
      { h: "7ஆம் வீடு — யுவதி (கூட்டாண்மை)", p: ["ஏழாம் வீடு திருமணம், துணைவர், வணிக கூட்டாண்மை, அனைத்து ஒருவருக்கொருவர் உறவுகளை ஆளுகிறது. இது முதல் வீட்டிற்கு நேர் எதிரே உள்ளது.", "இது பொது விவகாரங்கள், ஒப்பந்தங்கள், பொது மக்களையும் குறிக்கிறது.", "உடல் பாகங்கள்: கீழ் முதுகு, இனப்பெருக்க உறுப்புகள். காரகன்: சுக்கிரன்."] },
      { h: "8ஆம் வீடு — ரந்த்ர (மாற்றம்)", p: ["எட்டாம் வீடு ஆயுள், திடீர் நிகழ்வுகள், வாரிசு சொத்து, கூட்டு வளங்கள், மறைபொருள், ஆழமான மாற்றத்தை ஆளுகிறது. இது மிகவும் மர்மமான வீடு.", "ஆராய்ச்சி, மறைந்த விஷயங்களை ஆளுகிறது. பாதிக்கப்படும்போது கடினம், ஆதரிக்கப்படும்போது ஆழமான வலிமை.", "உடல் பாகங்கள்: இனப்பெருக்க உறுப்புகள். காரகன்: சனி."] },
      { h: "9ஆம் வீடு — தர்ம (அதிர்ஷ்டம் & நம்பிக்கை)", p: ["ஒன்பதாம் வீடு மிகவும் சுபமான வீடுகளில் ஒன்று — அதிர்ஷ்டம், உயர் ஞானம், தந்தை, குருமார்கள், புனித யாத்திரை, தர்மத்தை ஆளுகிறது.", "இது அருளைக் குறிக்கிறது — முற்பிறவி புண்ணியத்தால் வரும் அதிர்ஷ்டம். வலுவான ஒன்பதாம் வீடு நம்பிக்கை, நல்ல குரு தருகிறது.", "உடல் பாகங்கள்: இடுப்பு, தொடைகள். காரகன்: குரு, சூரியன் (தந்தை)."] },
      { h: "10ஆம் வீடு — கர்ம (தொழில் & அந்தஸ்து)", p: ["பத்தாம் வீடு தொழில், அந்தஸ்து, அதிகாரம், பொது நற்பெயரை ஆளுகிறது. இது ஜாதகத்தின் உச்சியில் உள்ளது — உலகம் காணும் உங்கள் சாதனை.", "உலகில் உங்கள் செயலையும், அதைத் தொடர்ந்து வரும் அங்கீகாரத்தையும் குறிக்கிறது.", "உடல் பாகங்கள்: முழங்கால், மூட்டுகள், எலும்புகள். காரகன்: சூரியன், புதன், குரு, சனி."] },
      { h: "11ஆம் வீடு — லாப (ஆதாயம் & வலைப்பின்னல்)", p: ["பதினொன்றாம் வீடு வருமானம், ஆதாயம், லாபம், நண்பர்கள், மூத்த உடன்பிறந்தோர், ஆசைகளின் நிறைவேற்றத்தை ஆளுகிறது.", "பெரிய குழுக்கள், சமூகங்கள், இலக்குகளின் சாதனையை ஆளுகிறது. வலுவான வீடு நிலையான வருமானம் தருகிறது.", "உடல் பாகங்கள்: கணுக்கால், கெண்டைக்கால். காரகன்: குரு."] },
      { h: "12ஆம் வீடு — வ்யய (இழப்பு & விடுதலை)", p: ["பன்னிரண்டாம் வீடு இழப்பு, செலவு, வெளிநாடு, தனிமை, தூக்கம், இறுதியில் ஆன்மீக விடுதலையை (மோட்சம்) ஆளுகிறது. இது விடுவிப்பின் வீடு.", "இழப்புடன் தொடர்புடையதாக இருந்தாலும், படுக்கை, தொண்டு, வெளிநாட்டு வாழ்க்கை, ஆழ்ந்த ஆன்மீக பயிற்சியின் வீடும் கூட.", "உடல் பாகங்கள்: பாதங்கள், இடது கண். காரகன்: சனி (இழப்பு), கேது (விடுதலை)."] },
      { h: "வீடுகளை ஒன்றாக படிப்பது", p: ["எந்த வீடும் தனியாக வேலை செய்யாது. வீட்டின் அதிபதி அந்த வீட்டின் ஆற்றலை அது அமர்ந்துள்ள இடத்திற்கு கொண்டு செல்கிறது.", "வீடுகள் இயற்கையான குழுக்களாக பிரிகின்றன: கேந்திரங்கள் (1,4,7,10) ஜாதகத்தின் தூண்கள்; திரிகோணங்கள் (1,5,9) அதிர்ஷ்டம்; துஸ்தானங்கள் (6,8,12) கடினம் மற்றும் வளர்ச்சி.", "எந்த வாழ்க்கைப் பகுதியையும் படிக்கும்போது மூன்றையும் சேர்த்துப் பாருங்கள்: வீடு, அதில் உள்ள கிரகங்கள், அதன் அதிபதியின் வலிமை."] },
    ],
  },
};

REFERENCES.planets.langs = {
  TA: {
    title: "9 கிரகங்கள்",
    subtitle: "நவகிரகங்கள் — குணங்கள், அர்த்தங்கள், காலங்கள்",
    intro: "வேத ஜோதிடம் ஒன்பது கிரகங்களை (நவகிரகம்) அங்கீகரிக்கிறது: சூரியன், சந்திரன், செவ்வாய், புதன், குரு, சுக்கிரன், சனி, மற்றும் இரண்டு நிழல் கிரகங்கள் ராகு மற்றும் கேது. ஒவ்வொரு கிரகமும் சில கருப்பொருள்களை ஆளுகிறது, சில ராசிகளை ஆளுகிறது, நிர்ணயிக்கப்பட்ட நீளமுள்ள மகாதசையை நடத்துகிறது.",
    sections: [
      { h: "சூரியன் — சூர்ய (ஆத்மா)", p: ["சூரியன் ஆத்மா, அகங்காரம், தந்தை, அதிகாரம், உயிர்ச்சக்தி, சுய வெளிப்பாட்டை குறிக்கிறது. இது கிரக அமைச்சரவையின் அரசன்.", "வலுவான சூரியன் நம்பிக்கை, தலைமை, நல்ல ஆரோக்கியம் தருகிறது. பலவீனமான சூரியன் குறைந்த நம்பிக்கை, அதிகாரத்துடன் சிக்கல் காட்டலாம்.", "ஆளுகிறது: சிம்மம். உச்சம்: மேஷம், நீசம்: துலாம். மகாதசை: 6 ஆண்டுகள். நாள்: ஞாயிறு."] },
      { h: "சந்திரன் — சந்த்ர (மனம்)", p: ["சந்திரன் மனம், உணர்ச்சிகள், தாய், பொது மக்கள், உணர்வின் உள் உலகத்தை குறிக்கிறது. வேத ஜோதிடத்தில் சந்திரன் லக்னத்தைப் போலவே முக்கியமானது.", "வலுவான சந்திரன் உணர்ச்சி நிலைத்தன்மை, அமைதியான மனம், புகழ் தருகிறது. பலவீனமான சந்திரன் உணர்ச்சி கொந்தளிப்பு காட்டலாம்.", "ஆளுகிறது: கடகம். உச்சம்: ரிஷபம், நீசம்: விருச்சிகம். மகாதசை: 10 ஆண்டுகள். நாள்: திங்கள்."] },
      { h: "செவ்வாய் — மங்கள (ஆற்றல் & தைரியம்)", p: ["செவ்வாய் ஆற்றல், தைரியம், செயல், ஆக்கிரமிப்பு, உடன்பிறந்தோர், சொத்து, உடல் உந்துதலை குறிக்கிறது. இது போர்வீரன்.", "வலுவான செவ்வாய் தைரியம், ஒழுக்கம், விளையாட்டுத் திறன் தருகிறது. பாதிக்கப்பட்ட செவ்வாய் கோபம், விபத்துகள் காட்டலாம்.", "ஆளுகிறது: மேஷம், விருச்சிகம். உச்சம்: மகரம், நீசம்: கடகம். மகாதசை: 7 ஆண்டுகள். நாள்: செவ்வாய்."] },
      { h: "புதன் — புத (புத்தி & தொடர்பு)", p: ["புதன் புத்திசாலித்தனம், தொடர்பு, தர்க்கம், வணிகம், எழுத்து, பகுப்பாய்வுத் திறனை குறிக்கிறது. இது விரைவான, தகவமைக்கக்கூடிய இளவரசன்.", "வலுவான புதன் கூர்மையான அறிவு, பேச்சுத்திறன், வணிக நுண்ணறிவு தருகிறது. பலவீனமான புதன் குழப்பமான சிந்தனை காட்டலாம்.", "ஆளுகிறது: மிதுனம், கன்னி. உச்சம்: கன்னி, நீசம்: மீனம். மகாதசை: 17 ஆண்டுகள். நாள்: புதன்."] },
      { h: "குரு — குரு (ஞானம் & அருள்)", p: ["குரு ஞானம், அறிவு, ஆசிரியர்கள், குழந்தைகள், செல்வம், தர்மம், அருளை குறிக்கிறது. இது மிகப்பெரிய சுபக் கிரகம்.", "வலுவான குரு ஞானம், நம்பிக்கை, தாராள மனம், அதிர்ஷ்டம் தருகிறது. குருவின் பார்வை எந்த வீட்டையும் பாதுகாக்கிறது.", "ஆளுகிறது: தனுசு, மீனம். உச்சம்: கடகம், நீசம்: மகரம். மகாதசை: 16 ஆண்டுகள். நாள்: வியாழன்."] },
      { h: "சுக்கிரன் — சுக்ர (காதல் & அழகு)", p: ["சுக்கிரன் காதல், அழகு, உறவுகள், கலை, ஆடம்பரம், சுகம், இன்பத்தை குறிக்கிறது. இது மற்றொரு சுபக் கிரகம்.", "வலுவான சுக்கிரன் வசீகரம், கலைத் திறமை, மகிழ்ச்சியான திருமணம் தருகிறது. வாகனங்கள், இனப்பெருக்க அமைப்பையும் ஆளுகிறது.", "ஆளுகிறது: ரிஷபம், துலாம். உச்சம்: மீனம், நீசம்: கன்னி. மகாதசை: 20 ஆண்டுகள். நாள்: வெள்ளி."] },
      { h: "சனி — சனி (ஒழுக்கம் & கர்மா)", p: ["சனி ஒழுக்கம், கர்மா, காலம், பொறுமை, சேவை, முதிர்ச்சியை குறிக்கிறது. இது மிகவும் கோரும் கிரகம், ஆனால் அதன் பாடங்கள் வாழ்நாள் முழுவதும் நீடிக்கும்.", "வலுவான சனி சகிப்புத்தன்மை, நேர்மை, உண்மையான முயற்சியால் அதிகாரம் தருகிறது. முழு விவரத்திற்கு சனி வழிகாட்டியைப் பார்க்கவும்.", "ஆளுகிறது: மகரம், கும்பம். உச்சம்: துலாம், நீசம்: மேஷம். மகாதசை: 19 ஆண்டுகள். நாள்: சனி."] },
      { h: "ராகு — வடக்கு முனை (ஆசை & லட்சியம்)", p: ["ராகு ஒரு உண்மையான கிரகம் அல்ல — சந்திரனின் வடக்கு முனை. இது உலக ஆசை, லட்சியம், வெறி, வெளிநாட்டு விஷயங்கள், தொழில்நுட்பத்தை குறிக்கிறது.", "ராகு அது தொடும் அனைத்தையும் பெருக்குகிறது. வியத்தகு வெற்றியையும் மாயையையும் தரக்கூடும்.", "மகாதசை: 18 ஆண்டுகள். ராகுவுக்கு சொந்த நாள் அல்லது ராசி ஆட்சி இல்லை."] },
      { h: "கேது — தெற்கு முனை (விரக்தி & விடுதலை)", p: ["கேது சந்திரனின் தெற்கு முனை, ராகுவுக்கு நேர் எதிரே. இது விரக்தி, ஆன்மீகம், முற்பிறவி தேர்ச்சி, விடுதலையை (மோட்சம்) குறிக்கிறது.", "ராகு ஆசைப்படும் இடத்தில், கேது துறக்கிறது. அது அமர்ந்துள்ள வீட்டின் விஷயங்களில் ஆழமான, உள்ளுணர்வு திறனை தருகிறது.", "மகாதசை: 7 ஆண்டுகள். கேதுவுக்கும் சொந்த நாள் அல்லது ராசி இல்லை."] },
      { h: "கிரக நட்புகள்", p: ["கிரகங்கள் ஒன்றுக்கொன்று நடுநிலையாக இல்லை — அவற்றுக்கு இயற்கையான நண்பர்கள், எதிரிகள், நடுநிலையாளர்கள் உள்ளனர்.", "சுருக்கமாக: சூரியன், சந்திரன், செவ்வாய், குரு ஒரு நட்புக் குழு; புதன், சுக்கிரன், சனி மற்றொன்று. சூரியனும் சனியும் இயற்கை எதிரிகள்.", "ஒரு கிரகம் நண்பனின் ராசியில் வசதியாக வெளிப்படுகிறது. எதிரியின் ராசியில் சிரமப்படுகிறது."] },
      { h: "கிரக காலங்கள் எவ்வாறு வேலை செய்கின்றன", p: ["ஒவ்வொரு கிரகமும் நிர்ணயிக்கப்பட்ட நீளமுள்ள மகாதசையை ஆளுகிறது: சூரியன் (6), சந்திரன் (10), செவ்வாய் (7), ராகு (18), குரு (16), சனி (19), புதன் (17), கேது (7), சுக்கிரன் (20) — மொத்தம் 120 ஆண்டுகள்.", "நீங்கள் எந்தக் காலத்தை நடத்துகிறீர்கள் என்பது பிறக்கும்போது சந்திரனின் நிலையைப் பொறுத்தது. ஒவ்வொரு பெரிய காலத்திற்குள்ளும் ஒன்பது அந்தர்தசைகள் இயங்குகின்றன.", "இதுவே இந்த செயலியின் தசா கால அம்சத்தின் பின்னணி இயந்திரம்."] },
    ],
  },
};

REFERENCES.saturn.langs = {
  TA: {
    title: "சனி பற்றி அனைத்தும்",
    subtitle: "கர்மா, ஒழுக்கம், விடுதலையின் கிரகம்",
    intro: "சனி (சனி பகவான்) வேத ஜோதிடத்தில் மிகவும் தவறாகப் புரிந்துகொள்ளப்படும் கிரகம். இது கடினம் மற்றும் தாமதம் என்ற பெயரைக் கொண்டுள்ளது, அது ஓரளவு மட்டுமே தகுதியானது. இந்த வழிகாட்டி முழுமையான படத்தைத் தருகிறது: சனி என்ன, அது உண்மையில் என்ன கேட்கிறது, அதன் மூன்று முக்கிய வெளிப்பாடுகள் எவ்வாறு உணரப்படுகின்றன.",
    sections: [
      { h: "சனி எளிய சொற்களில்", p: ["சனி 'மெதுவாக நகர்பவன்' என்று அறியப்படுகிறது. இது வானத்தை ஒருமுறை சுற்ற சுமார் இருபத்தொன்பதரை ஆண்டுகள் எடுக்கும். அந்த மெதுவு அதன் ஆழமான பாடம்: உண்மையான விஷயங்களுக்கு உண்மையான நேரம் தேவை.", "சனியைப் புரிந்துகொள்ள எளிய வழி: எளிதான மதிப்பெண்களை ஒருபோதும் தராத ஆசிரியரை கற்பனை செய்யுங்கள். ஒவ்வொரு மதிப்பெண்ணும் உண்மையான முயற்சியால் சம்பாதிக்கப்பட வேண்டும்.", "உங்கள் ஜாதகத்தில் சனியின் இடம் உங்கள் வாழ்க்கையின் மிகவும் கோரும், அர்த்தமுள்ள வேலை எங்கே நடக்கும் என்பதைக் காட்டுகிறது."] },
      { h: "சனி எதை ஆளுகிறது", p: ["சனி கர்மாவின் கிரகம் — கடந்த செயல்களின் விளைவுகள் நிகழ்காலத்தில் வருகின்றன. நேரத்துடன் மெதுவாக குவியும் அனைத்தையும் ஆளுகிறது: கட்டமைப்புகள், பொறுப்புகள், கடன்கள், ஞானம்.", "ஒழுக்கம் மற்றும் கட்டமைப்பு, தடைகள் மற்றும் தாமதம் (தண்டனை அல்ல, மறுவழிப்படுத்தல்), சேவை மற்றும் பணிவை ஆளுகிறது. உடலில் எலும்புகள், மூட்டுகள், பற்கள், தோல், முழங்கால்களை ஆளுகிறது.", "சனி பாபக் கிரகம் என்று வர்ணிக்கப்படுகிறது — ஆனால் 'பாபம்' என்றால் 'தீமை' அல்ல. சிற்பியின் உளி கல்லுக்கு கருணை காட்டாது, ஆனால் அந்த உராய்வு இல்லாமல் சிற்பம் இல்லை."] },
      { h: "சனியின் ஒழுக்கம் — சரியாக புரிந்துகொள்ளப்பட்டது", p: ["'ஒழுக்கம்' என்ற சொல் சனியைச் சுற்றி மிகவும் தவறாகப் புரிந்துகொள்ளப்பட்ட கருத்து. சனியின் தொன்மம் பாசறையில் உள்ள வீரன் அல்ல — அது தலைசிறந்த சிற்பி, ஆழமான நிலைத்தன்மையுடன் வேலை செய்பவர், ஆனால் உளிக்கு ஓய்வு தேவை என்பதையும் அறிந்தவர்.", "சனியின் பார்வையில் ஒழுக்கம் மூன்று விஷயங்களைக் குறிக்கிறது: தொடர்ந்து ஆஜராகி தொடங்கியதை முடித்தல்; கட்டமைப்பு ஒருமைப்பாடு; ஓய்வை கட்டமைப்பில் கட்டுதல்.", "சனி நிலைத்தன்மையால் ஆழமாக நகர்த்தப்படுகிறது, தீவிரத்தால் ஈர்க்கப்படுவதில்லை."] },
      { h: "சனி வேறுபடுத்தும் மூன்று தேவைகள்", p: ["சனி எந்த செயலையும் பற்றி ஒரு கேள்வி கேட்கிறது: இது ஆன்மாவை வளர்க்கிறதா அல்லது காயத்தை மரத்துப்போகச் செய்கிறதா?", "உடல் தேவைகள் (ஓய்வு, உணவு, உண்மையான உடல் இன்பம்) முழுமையாக மதிக்கப்படுகின்றன. ஆன்ம தேவைகள் (அர்த்தம், நோக்கம், படைப்பு வெளிப்பாடு) தீவிரமாக ஆதரிக்கப்படுகின்றன.", "அகங்காரத்தின் தேவைகள் (அங்கீகாரம், அந்தஸ்து) மட்டுமே கலைக்கப்படுகின்றன — கடுமையாக அல்ல, ஆனால் அகங்காரம் ஏங்கும் சரிபார்ப்பை நிலையாக திரும்பப் பெறுவதன் மூலம்."] },
      { h: "சடே சதி — சந்திரன் மீது சனியின் பயணம்", p: ["சடே சதி ('ஏழரை') என்பது உங்கள் ஜென்ம சந்திர ராசியை மையமாகக் கொண்ட மூன்று ராசிகளில் சனி பயணிக்கும் ஏழரை ஆண்டு காலம். இது ஒரே சந்திர ராசி உள்ள அனைவருக்கும் ஒரே நேரத்தில் நிகழ்கிறது.", "இது சுமார் இரண்டரை ஆண்டுகள் கொண்ட மூன்று கட்டங்களில் இயங்குகிறது: உயரும் (நுட்பமான கனம்), உச்சம் (சந்திரன் மீது நேரடியாக — மிகத் தீவிரமான கட்டம்), மறையும் (படிப்படியான நிவாரணம்).", "சடே சதி எதையோ எடுத்துச் செல்வது போல் உணர்கிறது — ஆனால் அது நீங்கள் உண்மையில் தேவைப்பட்டது அல்ல. நீங்கள் நினைத்ததை விட வலிமையானவர் என்பதை வெளிப்படுத்துகிறது."] },
      { h: "சனி மகாதசை — 19 ஆண்டு பாடத்திட்டம்", p: ["சனியின் மகாதசை பத்தொன்பது ஆண்டுகள் நீடிக்கும். சடே சதியைப் போலல்லாமல், மகாதசை உங்களுக்கு தனித்துவமானது, அதன் போது சனியின் ஜென்ம நிலை உங்கள் வாழ்க்கையின் இயக்க முறைமையாகிறது.", "இது ஐந்து கட்டங்களில் நகர்கிறது: புயல் 1, அருள் காலம், உணர்ச்சி பள்ளத்தாக்கு, புயல் 2, விடுதலை.", "சனி மகாதசை எடுக்காது — அது செம்மைப்படுத்துகிறது. அது அகற்றும் அனைத்தும் உண்மையில் உங்களுடையதாக இருக்கவில்லை."] },
      { h: "மற்ற காலங்களுக்குள் சனி அந்தர்தசை", p: ["சனி ஒவ்வொரு கிரகத்தின் மகாதசைக்குள்ளும் ஒரு அந்தர்தசையாக வருகிறது. அதன் தரம் புரவலன் கிரகத்தைப் பொறுத்தது.", "குருவின் காலத்திற்குள் அது மிகவும் பயனுள்ள கலவையை உருவாக்குகிறது — ஞானம் மற்றும் ஒழுக்கம். ராகுவுக்குள், மிகவும் கோருகிறது.", "புரவலன் எதுவாக இருந்தாலும், சனியின் காலம் எப்போதும் ஒன்றையே வெகுமதி அளிக்கிறது — காணப்பட வேண்டிய தேவையின்றி உண்மையில் செய்யத் தகுந்ததை செய்தல்."] },
      { h: "பரிகாரங்கள் — சனியுடன் வேலை செய்தல்", p: ["முதலில் ஒரு கொள்கை தெளிவாக இருக்க வேண்டும்: எந்த பரிகாரமும் சனியின் பாடத்தை தவிர்க்காது. பரிகாரங்கள் சனியின் ஆற்றலுடனான உங்கள் உறவின் தரத்தை மாற்றுகின்றன.", "நடைமுறை பரிகாரங்களில் சனி சேவை (வயதானவர்கள், உழைப்பாளர்களுக்கு பெயர் தெரியாமல் சேவை, சனிக்கிழமைகளில்), காகங்களுக்கு உணவளித்தல், மகாமிருத்யுஞ்சய மந்திரம் அடங்கும்.", "மாற்ற முடியாத அடித்தளம் உங்கள் சொந்த துன்பத்தில் அகங்காரத்தின் பங்கைப் பற்றிய நேர்மையான சுய விழிப்புணர்வு."] },
      { h: "முடிவுரை", p: ["சனி உங்களை உண்மையில் ஆக முடிந்ததை விட குறைவாக நிலைக்க விடாத கிரகம். அது உங்களை அரவணைப்புடன் சந்திக்காது — நேர்மையுடன் சந்திக்கிறது.", "விழிப்புணர்வுடன் சனி காலத்தை முடிக்கும் நபர், அதில் நுழைந்த அதே நபராக இருப்பதில்லை.", "அது கொடுமை அல்ல. அது கிரக அமைப்பில் கிடைக்கும் மிகவும் அர்ப்பணிப்புள்ள கற்பித்தல் வடிவம்."] },
    ],
  },
};

if (typeof window !== "undefined") window.REFERENCES = REFERENCES;
